language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-dj' ]; then cd .. && eval "mv $currentfolder generator-dj" && cd generator-dj; fi

